let arr = [1, 3, 5, 7, 9, 11];
console.log(arr);
arr.push(13);
console.log(arr);
console.log(arr.length);
console.log(arr.indexOf(7));
console.log(arr.reverse());
arr.pop();
console.log(arr);
console.log(arr.concat(15));